feat(episode): add #2
podcast-bokueki/bokueki pull request #8
Opened 2024-10-11 13:01 UTC by naokiur

# Summary
* add  `episode#2` , description idea and some image files,
* change directory structure
    * because some episodes need some image files. I would like to group them by directory.

# Point

* コンテンツ（ショーノートっぽいところ）はジャストアイデアなので他になにかあれば…
* コンテンツの段落の中で画像いれてったらコンテンツ全体が縦長になってしまったので分けました
* index.mdの `### [episode. 2](./0002/index.md) ` のところにタイトルをいれるんでしたっけ…

2024-10-11 13:08 UTC, talasago commented
docs/0002.mdが正しいはずです！

2024-10-11 13:17 UTC, talasago commented on docs/0002/index.md
> +   2. 「Podcastやりたいプレゼン」をしたの話
```suggestion
   2. 「Podcastやりたいプレゼン」をした話
```
かな！

2024-10-11 13:17 UTC, talasago commented on docs/0002/index.md
> +<iframe src="" height="102px" width="400px" frameborder="0" scrolling="no"></iframe>
📋️ここにspotifyのリンクが入る

2024-10-11 13:17 UTC, talasago commented on docs/0002/index.md
> +      3. 「あとで決めること」
```suggestion
   2. 肯定文で表現した方が良いよね
```
とかの方が好みかも

2024-10-11 13:17 UTC, talasago commented on docs/0002/index.md
> +![完成系](./fixed_why_are_we_here.png)
リンクがダブってる？？

2024-10-11 13:18 UTC, talasago commented on docs/index.md
> +### [episode. 2](./0002/index.md)
新しい方を上にしたいかも（降順）

2024-10-11 13:19 UTC, talasago commented
一旦スマホから確認しました！

2024-10-11 13:20 UTC, talasago commented
> index.mdの ### [episode. 2](./0002/index.md) のところにタイトルをいれるんでしたっけ…

前回いれてないし入れなくても大丈夫かと！

2024-10-11 13:41 UTC, naokiur commented on docs/0002/index.md
> +![完成系](./fixed_why_are_we_here.png)
あらあら… 😱

2024-10-12 02:15 UTC, naokiur commented on docs/0002/index.md
> +![完成系](./fixed_why_are_we_here.png)
fix! 

https://github.com/podcast-bokueki/bokueki/commit/c449504473731d8423f02a84a92d49cd055d40b0

2024-10-12 02:20 UTC, naokiur commented on docs/index.md
> +### [episode. 2](./0002/index.md)
fix!

https://github.com/podcast-bokueki/bokueki/commit/70d9571cb59195d0836bf1f840daa7a2141ad06a

2024-10-12 02:46 UTC, naokiur commented on docs/0002/index.md
> +配信開始日: 2024/10/12
@talasago 
すみません火曜日が10/12だとおもってました
10/12土曜日だわ
つよきの公開日書いてたすみません

2024-10-12 07:40 UTC, talasago commented on docs/0002/index.md
> +配信開始日: 2024/10/12
強気でも良いですよ！

2024-10-12 07:43 UTC, talasago requested changes

2024-10-12 07:43 UTC, talasago commented on docs/0002/index.md
> +---
https://github.com/podcast-bokueki/bokueki/pull/8#issuecomment-2407382149
すみません、これだけあとご対応いただけると…！
こうしないとホームページのエピソード毎のURLに統一感がなくなってしまうので！
今エピソード1は/docs/0001だと思うので

2024-10-12 07:44 UTC, talasago commented on docs/0002/index.md
> +---
実は今回からパスを変えたいとか意図あるでしょうか…！？

2024-10-13 01:10 UTC, naokiur commented on docs/0002/index.md
> +---
@talasago 
アッただしいってそういうことか
ディレクトリ構造とURLを変えたいです！
今のURLはこうでした！

<img width="632" alt="image" src="https://github.com/user-attachments/assets/c702143c-bb15-4a18-8776-84b8ecf6cc96">

episode 1もディレクトリつくっていきたいです！

episode 2のローカル実行時のURLはこんな形です！
<img width="621" alt="image" src="https://github.com/user-attachments/assets/ae72eb1c-983b-4c8e-83ef-f32b3c80719e">

2024-10-13 11:04 UTC, talasago approved these changes
LGTM

2024-10-13 11:05 UTC, talasago commented on docs/0002/index.md
> +---
了解です！
一回下記のような細かい部分で気になる部分はあるのですが、一旦マージしましょう！

----
http://localhost:4000/bokueki/0002/だと動くけど、http://localhost:4000/bokueki/0002だと動かないのが少々気になりますが...
さいごに/がついている宛先がページなのに違和感を覚えます。ただ解決策は持ってないです,,,

2024-10-14 11:21 UTC, merged